### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kevinblanco** [josephj/react-icalendar-link#1]
Using a react app created with `create-react-app` trows the following error: 
```
webpack:///./client/node_modules/react-icalendar-link/dist/index.es.js?:137
 var ua = window.navigator.userAgent;
 
[1] ReferenceError: window is not defined
[1]     at isIOSChrome (webpack:///./client/node_modules/react-icalendar-link/dist/index.es.js?:137:14)
```

**Comment by spidgorny** [comment]
This also happens when doing SSR with nextjs. React code is being executed on the nodejs, which has no concept of "window".

Wrapping in <NoSSR> doesn't help because isIOSChrome() function is called during "import".
```
<NoSSR>
	<ICalendarLink event={props.event}>
		Add to Calendar
	</ICalendarLink>
</NoSSR>
```

Can we avoid running this code during "import" and move this function to the render time? Please.

**Comment by josephj** [comment]
@kevinblanco I am not sure why it could cause the undefined `window` issue in CRA. 

@spidgorny I moved the `isSupported` to method from property. Not sure if this fixes your issue.
